### ISSUE TITLE
some packages will not download

### ISSUE THREAD

**Issue by markghayden** [whitequark/opam-cross-android#14]
easy-format and biniou won't download.  --M

+ env ANDROID_LEVEL=15 ANDROID_ABI=linux_eabi ANDROID_ARCH=armv7 opam install ocaml-android yojson-android biniou-android easy-format-android
The following actions will be performed:
  - install android-ndk-linux   11c                     [required by conf-android]
  - install conf-android        1                       [required by ocaml-android32]
  - install ocaml-android32     4.02.3                  [required by ocaml-android]
  - install ocaml-android       4.02.3
  - install easy-format-android 1.2.0 
  - install biniou-android      1.0.10
  - install yojson-android      1.3.2 
===== 7 to install =====
Do you want to continue ? [Y/n] 
y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] curl: code 404 while downloading
        http://mjambon.com/releases/easy-format/easy-format-1.2.0.tar.gz
[ERROR] curl: code 404 while downloading
        http://mjambon.com/releases/biniou/biniou-1.0.10.tar.gz
[yojson-android.1.3.2] https://github.com/mjambon/yojson/archive/v1.2.0.tar.gz downloaded

**Comment by markghayden** [comment]
Sorry... also ndk-linux-android seems to fail.  See below


+ env ANDROID_LEVEL=15 ANDROID_ABI=linux_eabi ANDROID_ARCH=armv7 opam install ocaml-android yojson-android biniou-android easy-format-android
The following actions will be performed:
  - install android-ndk-linux   11c                     [required by conf-android]
  - install conf-android        1                       [required by ocaml-android32]
  - install ocaml-android32     4.02.3                  [required by ocaml-android]
  - install ocaml-android       4.02.3
  - install easy-format-android 1.2.0 
  - install biniou-android      1.0.10
  - install yojson-android      1.3.2 
===== 7 to install =====
Do you want to continue ? [Y/n] 
y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] curl: code 404 while downloading
        http://mjambon.com/releases/easy-format/easy-format-1.2.0.tar.gz
[ERROR] curl: code 404 while downloading
        http://mjambon.com/releases/biniou/biniou-1.0.10.tar.gz
[yojson-android.1.3.2] https://github.com/mjambon/yojson/archive/v1.2.0.tar.gz downloaded
[ocaml-android32.4.02.3] http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.3.tar.gz downloaded
[ERROR] The sources of the following couldn't be obtained, aborting:
          - android-ndk-linux.11c
          - biniou-android.1.0.10
          - easy-format-android.1.2.0
        (This may be fixed by running 'opam update')
debian64%

**Comment by whitequark** [comment]
`android-ndk-linux.11c` downloads OK over here, what happened is opam decided to quit early because of the other failures.

**Comment by markghayden** [comment]
The problem was that my /tmp was filling up.... 2GB was not enough
