### ISSUE TITLE
Extra '/' in ocaml native runtime library objects when hosted on MacOS

### ISSUE THREAD

**Issue by markghayden** [whitequark/opam-cross-android#17]
Also there is a strange '/' file included in the archive.

% ar t -Lv /Users/mhayden/.opam/4.02.3+32bit/android-sysroot/lib/ocaml/libasmrun.a
---------       0/0         15490 Apr 22 12:25 2016 /
rw-rw-r--     501/20         4508 Apr 22 12:24 2016 startup.o/
rw-rw-r--     501/20         1008 Apr 22 12:24 2016 main.o/
rw-rw-r--     501/20         4248 Apr 22 12:24 2016 fail.o/
rw-rw-r--     501/20         5192 Apr 22 12:24 2016 roots.o/
rw-rw-r--     501/20         5180 Apr 22 12:24 2016 globroots.o/
rw-rw-r--     501/20         4612 Apr 22 12:24 2016 signals.o/
rw-rw-r--     501/20         2024 Apr 22 12:24 2016 signals_asm.o/
rw-rw-r--     501/20         2776 Apr 22 12:24 2016 misc.o/
rw-rw-r--     501/20         5764 Apr 22 12:24 2016 freelist.o/
rw-rw-r--     501/20         9204 Apr 22 12:24 2016 major_gc.o/
rw-rw-r--     501/20         5904 Apr 22 12:24 2016 minor_gc.o/
rw-rw-r--     501/20         6360 Apr 22 12:24 2016 memory.o/
rw-rw-r--     501/20         3376 Apr 22 12:24 2016 alloc.o/
rw-rw-r--     501/20         5436 Apr 22 12:24 2016 compare.o/
rw-rw-r--     501/20        11948 Apr 22 12:24 2016 ints.o/
rw-rw-r--     501/20         7784 Apr 22 12:24 2016 floats.o/
rw-rw-r--     501/20         4112 Apr 22 12:24 2016 str.o/
rw-rw-r--     501/20         6300 Apr 22 12:24 2016 array.o/
rw-rw-r--     501/20        11756 Apr 22 12:24 2016 io.o/
rw-rw-r--     501/20        12712 Apr 22 12:24 2016 extern.o/
rw-rw-r--     501/20        13056 Apr 22 12:24 2016 intern.o/
rw-rw-r--     501/20         4560 Apr 22 12:24 2016 hash.o/
rw-rw-r--     501/20         7736 Apr 22 12:24 2016 sys.o/
rw-rw-r--     501/20         4344 Apr 22 12:24 2016 parsing.o/
rw-rw-r--     501/20         9836 Apr 22 12:24 2016 gc_ctrl.o/
rw-rw-r--     501/20         1412 Apr 22 12:24 2016 terminfo.o/
rw-rw-r--     501/20         5256 Apr 22 12:24 2016 md5.o/
rw-rw-r--     501/20         3584 Apr 22 12:24 2016 obj.o/
rw-rw-r--     501/20         1920 Apr 22 12:24 2016 lexing.o/
rw-rw-r--     501/20         2844 Apr 22 12:24 2016 printexc.o/
rw-rw-r--     501/20         2652 Apr 22 12:24 2016 callback.o/
rw-rw-r--     501/20         4340 Apr 22 12:24 2016 weak.o/
rw-rw-r--     501/20         6572 Apr 22 12:24 2016 compact.o/
rw-rw-r--     501/20         4108 Apr 22 12:24 2016 finalise.o/
rw-rw-r--     501/20         2248 Apr 22 12:24 2016 custom.o/
rw-rw-r--     501/20         3184 Apr 22 12:24 2016 unix.o/
rw-rw-r--     501/20         5312 Apr 22 12:24 2016 backtrace.o/
rw-rw-r--     501/20         4124 Apr 22 12:24 2016 natdynlink.o/
rw-rw-r--     501/20         1084 Apr 22 12:24 2016 debugger.o/
rw-rw-r--     501/20         2036 Apr 22 12:24 2016 meta.o/
rw-rw-r--     501/20         2100 Apr 22 12:24 2016 dynlink.o/
rw-rw-r--     501/20         2744 Apr 22 12:24 2016 arm.o/

**Comment by whitequark** [comment]
What the heck...

**Comment by markghayden** [comment]
I know… it is a little crazy.  Unfortunately, this breaks our build scripts.  —Mark

**Comment by markghayden** [comment]
The problem was using MacOS host 'ar' command.  Apparently, the formats used for ar are different (?!?!)

**Comment by whitequark** [comment]
Yes, that's what I suspected although had not found a chance to verify yet. How did you fix it?

**Comment by markghayden** [comment]
I fixed the builds to be more careful about using the ar for the target.  I’ve done alot of cross-compilation, but I hadn’t run into that kind of incompatibility with ar before on tacos.

—Mark
