### ISSUE TITLE
Android directory tree seem to not allow for simultaneous armv7 and x86 cross-compilers

### ISSUE THREAD

**Issue by markghayden** [whitequark/opam-cross-android#18]
We haven't tried to build x86 android cross compilers yet, but it seems the directory tree would be an issue.  For example, it seems the armv7 and x86 toolchains would both install in the same android-sysroot directory:

.opam/4.02.3+32bit/android-sysroot

**Comment by whitequark** [comment]
Yes. That's working exactly as intended. There can only be one cross-compiler per opam switch; use something like `opam switch 4.02.3+android-arm32 --alias-of 4.02.3+32bit`, `opam switch 4.02.3+android-x86_32 --alias-of 4.02.3+32bit`, etc to create a switch per deployment target, and then install the packages you need in every switch independently (the switches are not linked in any way).

I know, annoying. There is nothing I can do about it and still be able to maintain the cross-switches in a sane way. It's an opam deficiency. I've suggested a fix but no one has implemented it yet.

**Comment by markghayden** [comment]
Thanks for the explanation and work-around —M
