### ISSUE TITLE
Support for several ABIs

### ISSUE THREAD

**Issue by vouillon** [whitequark/opam-cross-android#2]
The toolchain is currently configured to target the ARMv5TE architecture.

It should be possible to generate ARMv7 code as well, as it is supported by most Android devices, uses hard floating points, and is more compact (OCaml will generate Thumb-2 instructions by default). You can have a look at how https://github.com/vouillon/ocaml-android does it. I think the selection should be done through an environment variable as with `ANDROID_LEVEL`.

The x86 architecture should be supported as well.

A concern is that the Android NDK is going to be duplicated for each all compiler. Maybe one can just extract the relevant platform and toolchain?

**Comment by lingz** [comment]
Amy news on how to compile for x86 at current? Is it only possible with @vouillion 's package and not this one?

**Comment by whitequark** [comment]
@lingz you should be able to build for x86 by creating a separate switch and installing the compiler with `ANDROID_ARCH` set correctly. I don't recall offhand what the right value is but something like `x86` might work?

**Comment by lingz** [comment]
For creating a separate switch do you mean to fork the opam-android32 package and modify the files there to add a case for arch=x86?

**Comment by whitequark** [comment]
Ah sorry. I forgot that I haven't pushed the changes yet that make switching platforms simple. I should do it within a week or so.

**Comment by lingz** [comment]
Ah that would be great. Thanks and look forward to it.

**Comment by whitequark** [comment]
Done (both hard-float ABI support and x86 support); please see README to see how would this be used.
