### ISSUE TITLE
64 bits ARM target?

### ISSUE THREAD

**Issue by yunxing** [whitequark/opam-cross-android#25]
Hey, 

I'm trying cross-compile to my phone running on ARM 64 but realized it is not supported yet. Just curious what would it take to support that?

**Comment by whitequark** [comment]
Should be possible by setting the right values to the environment variables (see this [opam file](https://github.com/whitequark/opam-cross-android/blob/master/packages/conf-android.1/opam) for reference).

**Comment by yunxing** [comment]
@whitequark Thanks. 
'''
ARCH=arm64 SUBARCH=arm64 SYSTEM=linux_eabi CCARCH=arm64 TOOLCHAIN=aarch64-linux-android-4.9 TRIPLE=aarch64-linux-android LEVEL=23 STLVER=4.9 STLARCH=arm64-v8a
'''

This env seems to work testing.

**Comment by yunxing** [comment]
I'm trying to run the helloworld example on Android through adb, but got and error:
![image](https://cloud.githubusercontent.com/assets/1017689/19790199/3933a44a-9c6b-11e6-8812-312dee1a1688.png)
Does that mean I need to add -fPIC to the gcc command?

**Comment by yunxing** [comment]
hmm, I guess in this case `ocamlopt` has to produce a location independent assembly code. Is there any way to do that?

**Comment by yunxing** [comment]
ah, nvm. I just needed to pass "pie" to the linker.

**Comment by whitequark** [comment]
Added to README, thanks for testing
