### ISSUE TITLE
ocamlbuild git url

### ISSUE THREAD

**Issue by Kakadu** [whitequark/opam-cross-android#26]
I have a weird issue about your ocamlbuild repo.  I needed to do 

    opam pin add ocamlbuild https://github.com/whitequark/ocamlbuild.git

instead of 

    opam pin add ocamlbuild https://github.com/whitequark/ocamlbuild

to compile it successfully. Don't know is it a general opam thing or opam-2.0 related.

**Comment by whitequark** [comment]
You are right, I've changed that.
