### ISSUE TITLE
Can't install conf-android on 32-bit system

### ISSUE THREAD

**Issue by mryau** [whitequark/opam-cross-android#29]
I'm use Ubuntu 14.04 LTS 32-bit version.
`ARCH=arm SUBARCH=armv7 SYSTEM=linux_eabihf CCARCH=arm TOOLCHAIN=arm-linux-androideabi-4.9 TRIPLE=arm-linux-androideabi STLVER=4.9 STLARCH=armeabi   opam install conf-android`
says
```
The following dependencies couldn't be met:
  - conf-android -> android-ndk-darwin >= 11c
  - conf-android -> android-ndk-linux >= 11c
Your request can't be satisfied:
  - android-ndk-darwin>=11c is not available because your system doesn't comply with os = "darwin".
  - android-ndk-linux>=11c is not available because your system doesn't comply with os = "linux" & arch = "x86_64".
```
I've played with LEVEL=`[9.. 11]` and `TOOLCHAIN=arm-linux-androideabi-[4.6 .. 4.9]` but it not resolved my problem.
How should I install conf-android on 32-bit host machines?

**Comment by whitequark** [comment]
There is no Android NDK for 32-bit host machines: https://developer.android.com/ndk/downloads/index.html. Therefore you cannot do that.
