### ISSUE TITLE
Documentation is missing an example

### ISSUE THREAD

**Issue by cholewa1992** [whitequark/opam-cross-android#30]
Hi; I find both this and your iOS cross compiler very difficult to use as there is no examples on how to actually call ocaml code from e.g. an android activities. It would be extremely helpful if such examples was included!

**Comment by whitequark** [comment]
Sorry but it is not my job to educate you on top of maintaining a cross-toolchain free of charge. There are multiple examples of using OCaml from other languages on the web. Look up using JNI and also see http://www.mega-nerd.com/erikd/Blog/CodeHacking/Ocaml/calling_ocaml.html.
